version = 0.1
[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todo-list-aws-production"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hwr6ts9w4rff"
s3_prefix = "todo-list-aws"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
